# Generated by Django 5.1.5 on 2025-01-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('people_count', models.CharField(max_length=20)),
                ('hunger_level', models.CharField(max_length=50)),
                ('food_type', models.CharField(max_length=20)),
                ('spicy_level', models.IntegerField(blank=True, null=True)),
                ('oil_level', models.IntegerField(blank=True, null=True)),
                ('texture_level', models.IntegerField(blank=True, null=True)),
                ('taste_level', models.IntegerField(blank=True, null=True)),
                ('no_preference', models.BooleanField(default=False)),
            ],
        ),
    ]
